#!/bin/bash
echo "Installing Homebrew, a package manager that will make computer set up a lot easier. This process also installs Git"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
clear

echo "Updating the binaries for nodejs, python and ruby so we know everyone is running the same version. Installs cask to make other binary installs simpler"
brew install nodejs python ruby cask

echo "Install firefox, chrome, sublime text, atom, textwrangler to make sure everyone is running the same versions"
brew cask install firefox google-chrome sublime-text atom textwrangler
clear

brew doctor

echo "Installing Oh My ZSH so we all have the same shell and it's tailored to Git!"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"
