#!/bin/bash
echo "Installing Homebrew"
bash "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
clear

echo "Level the playing field for firefox and chrome"
brew install --force --cask firefox google-chrome

echo "Install sublime-text, atom, slack"
brew install --cask --force sublime-text atom slack
clear

brew doctor

echo "Setup atom extensions"
apm install atom-beautify pigments less-than-slash seti-ui open-in-browsers
curl -fsSL https://raw.githubusercontent.com/tc-mccarthy/edu/master/configs/atom.cson > ~/.atom/config.cson

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Configuring terminal profile"
cd ~/Downloads
curl -O https://raw.githubusercontent.com/tc-mccarthy/edu/master/scripts/CUNY.terminal
open CUNY.terminal

clear
echo "Install complete!"
