#!/bin/bash
echo "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

## M1 chip-specific logic
if [[ "$(uname -m)" == "arm64" ]]; then
  echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zprofile
  export PATH="/opt/homebrew/bin:${PATH}"
fi

clear

echo "Level the playing field for firefox and chrome"
brew install --force --cask firefox google-chrome

echo "Install sublime-text, atom, slack, vscode"
brew install --cask --force sublime-text atom slack visual-studio-code
clear

brew doctor

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Configuring terminal profile"
cd ~/Downloads
curl -O https://raw.githubusercontent.com/tc-mccarthy/edu/master/scripts/CUNY.terminal
open CUNY.terminal

clear
echo "Install complete!"
