#!/bin/bash
echo "Installing Homebrew, a package manager that will make computer set up a lot easier. This process also installs Git"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
clear

echo "Updating the binaries for nodejs, python and ruby so we know everyone is running the same version. Installs cask to make other binary installs simpler"
brew install nodejs python ruby cask

echo "Install sublime text, atom, textwrangler and mamp to make sure everyone is running the same versions"
brew cask install sublime-text atom mamp
clear

echo "Setup atom extensions"
apm install project-view project-manager atom-beautify less-than-slash

echo "Configuring atom"
curl -fsSL https://raw.githubusercontent.com/tc-mccarthy/edu/master/configs/atom.cson > ~/.atom/config.cson

echo "Installing Oh My ZSH so we all have the same shell and it's tailored to Git!"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"
