#!/bin/bash
echo "Installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
clear

echo "Installing nodejs, python, ruby, cask, php-cs-fixer"
brew install --force nodejs python3 ruby cask php-cs-fixer

echo "Level the playing field for firefox and chrome"
brew cask install --force firefox google-chrome

echo "Install sublime-text, atom, slack and mamp"
brew cask install --force sublime-text atom slack mamp
clear

brew doctor

echo "Setup atom extensions"
apm install atom-beautify pigments less-than-slash seti-ui
curl -fsSL https://raw.githubusercontent.com/tc-mccarthy/edu/master/configs/atom.cson > ~/.atom/config.cson
alias pip="pip3"
pip install --upgrade sqlparse

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"
